auctions/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
app_name = 'auctions'
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("login", views.login_view,name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"), 
    path("createListing", views.createListing, name="create"),
    path("item/<int:Id>/", views.viewItem, name="item"), 
    path("watchList/<int:Id>/", views.addOrRemoveToWatchList, name="watchList"),
    path("watchList", views.viewWatchList, name = "watch"),
    path("categories", views.categoriesList, name="categories"), 
    path("category/<str:name>", views.showCategoryItems, name="category")
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext as _


class User(AbstractUser):
    pass
class AuctionListing(models.Model):
    class categories(models.TextChoices):
        fashion = 'Fsh', _('Fashion')
        toys = 'Ty', _('Toys')
        electronics = 'Elec', _('Electronics')
        books = 'Book', _('Books')
        sports = 'sports', _('Sports')
        none = '', _('None')
    title = models.CharField(max_length=64)
    description = models.TextField()
    image = models.ImageField(default='', upload_to='images/')
    initialBid = models.IntegerField(default = 0)
    category = models.CharField(max_length=64, choices = categories, default = categories.none, blank = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "owner")
    isActive = models.BooleanField(default=True)
    def __str__(self):
        return f"{self.title}"
    def get_category_full_name(self):
       return self.get_category_display()

class Bid(models.Model):
    bidOn = models.ForeignKey(AuctionListing, on_delete = models.CASCADE, related_name = "bidOn")
    bid = models.IntegerField()
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "buyer")
    def __str__(self):
        return f"{self.buyer.first_name} made {self.bid} on {self.bidOn.title}"
    
    
class Comments(models.Model):
    commentedOn = models.ForeignKey(AuctionListing, on_delete = models.CASCADE, related_name = "commentsOn")
    Comment = models.TextField()
    commentor = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "commentor")
    def __str__(self):
        return f"{self.commentor} comment '{self.Comment}' on {self.commentedOn.title}" 
class WatchList(models.Model):
    watchUser = models.ForeignKey(User,on_delete = models.CASCADE)
    products = models.ManyToManyField(AuctionListing)

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from . models import AuctionListing, Bid, Comments, WatchList
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
from django.utils.safestring import mark_safe
from django.core.validators import MinValueValidator
from django.contrib.auth.decorators import login_required
from django.db.models import Max
from .models import User


def index(request):
    return render(request, "auctions/index.html", {
        'auctionlist' : AuctionListing.objects.all(), 
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))

class createListingForm(forms.Form):
    title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
        required=True,
        label=mark_safe('Title <span class="required">*</>')
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        required=True,
        label=mark_safe('Description <span class="required">*</>')
    )
    initialBid = forms.IntegerField(
        required=True,
        validators=[MinValueValidator(1)],
        label=mark_safe('Initial Bid <span class="required">*</>')
    )
    picture = forms.ImageField(
        label = 'Choose an Image:',
        required=False
    )
    category = forms.ChoiceField(
        label = 'Category:',
        widget=forms.Select(attrs={'class': 'form-control'}),
        choices=AuctionListing.categories.choices,
        required=False
    )
    initialBid.widget.attrs.update({'class': 'form-control', 'placeholder': "Initial Bid"})
    picture.widget.attrs.update({'class': 'form-control'})
    
@login_required(login_url='auctions:login')
def createListing(request):
    if request.method == "POST":
        form = createListingForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            initialBid = form.cleaned_data["initialBid"]
            picture = form.cleaned_data["picture"]
            category = form.cleaned_data["category"]
            if User.is_authenticated:
                ac = AuctionListing(title=title, description=description, initialBid=initialBid, image=picture, category=category, owner = request.user)
                ac.save()
                return HttpResponseRedirect(reverse('auctions:index'))
        else:
            return render(request, 'auctions/create.html', {
                'form' : form
            })
    form = createListingForm(label_suffix='')
    return render(request, "auctions/create.html", {
        'form': form,
    })
def isOwner(request, ac):
    if request.user.is_authenticated:
        if request.user == ac.owner:
            return True
    return False
def getStatus(ac):
    if ac.isActive:
        return "Open"
    return "Closed"
def isWinner(request, noOfBids, ac, highestBid):
    if request.user.is_authenticated and ac.isActive == False and isOwner(request, ac) == False:
        if noOfBids != 0:
            winner = Bid.objects.filter(bidOn = ac, bid = highestBid)
            if winner is not None:
                if winner.first().buyer == request.user:
                    return True
    return False 
class CommentForm(forms.Form):
    comment = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write your comment here...'}),
        required=False,
        label='',
        error_messages={'required': ''}
    )
    comment.widget.attrs.update(required = True)
def viewItem(request, Id):
    ac = AuctionListing.objects.get(id=Id)
    highestBid = Bid.objects.filter(bidOn = ac).aggregate(Max('bid'))['bid__max']
    # To Check if item is in user watchlist or not
    noOfBids = Bid.objects.filter(bidOn = ac).count()
    flag = True
    message = None
    form = CommentForm(request.POST)
    if request.user.is_authenticated:
        try:
            wc = WatchList.objects.get(watchUser = request.user)
        except WatchList.DoesNotExist:
            flag = False
        if flag:
            if not wc.products.contains(ac):
                flag = False
    else:
        flag = False
    Owner = isOwner(request, ac)
    if request.method == "POST" and Owner:
        ac.isActive=False
        ac.save()
    elif request.method == "POST":
        if not request.user.is_authenticated:
            return render(request, 'auctions/login.html')
        if 'comment_submit' in request.POST:
            if form.is_valid():
                comment = form.cleaned_data["comment"]
                if request.user.is_authenticated:
                    commentModel = Comments(commentedOn = ac, Comment = comment, commentor = request.user)
                    commentModel.save()
        else:
            newBid = int(request.POST["bidInput"])
            if (highestBid is None or newBid > highestBid) and newBid > ac.initialBid:
                newObj = Bid.objects.create(bidOn = ac, bid = newBid, buyer = request.user)
                highestBid = newBid
                noOfBids += 1
                newObj.save()
            else:
                message = "Your bid Should be greater than current bid"
        
        
    if highestBid is None:
        highestBid = ac.initialBid  
    getComments = None
    try:
        getComments = Comments.objects.filter(commentedOn = ac).all()
    except Comments.DoesNotExist:
        pass
    return render(request, 'auctions/item.html', {
        'auctionList': ac, 
        'isWatchListItem' : flag,
        'isOwner' : Owner,
        'status' : getStatus(ac),
        'highestBid' : highestBid,
        'noOfBids': noOfBids,
        'message' : message, 
        'isWinner': isWinner(request, noOfBids, ac, highestBid),
        'comments': getComments,
        'commentForm' : form
    })
def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

@login_required(login_url='auctions:login')
def addOrRemoveToWatchList(request, Id):
    wc, created = WatchList.objects.get_or_create(watchUser = request.user)
    if request.method == "POST" and request.user.is_authenticated:
        ac = AuctionListing.objects.get(id=Id)
        if wc.products.contains(ac):
            wc.products.remove(ac)
            return HttpResponseRedirect(reverse("auctions:item",kwargs={'Id': Id}))
        else:
            wc.products.add(ac)
        wc.save()
    if (wc):
            products = wc.products.all()
    else:
            products =[]
    return render(request, 'auctions/watchList.html', {
        'products': products,
        'isEmpty' : len(products) == 0
    })
@login_required(login_url='auctions:login')
def viewWatchList(request):
    flag = True
    try:
        wc = WatchList.objects.get(watchUser = request.user)
    except WatchList.DoesNotExist:
        flag = False
    if flag:
        products = wc.products.all()
    else:
        products = []
    return render(request, 'auctions/watchList.html', {
        'products': products,
        'isEmpty' : len(products) == 0
    })
    
def categoriesList(request):
    categories = [category for _, category in AuctionListing.categories.choices]
    categories.remove('None')
    return render(request, 'auctions/categories.html', {
        'categories': categories
    })
def showCategoryItems(request, name):
    cat = extractCategory(name)
    ac = AuctionListing.objects.filter(category = cat).all()
    return render(request, 'auctions/category.html', {
        'category': name, 
        'auctionlist': ac
    })
def extractCategory(name):
    if name == 'Fashion':
        return 'Fsh'
    elif name == 'Toys':
        return 'Ty'
    elif name == 'Electronics':
        return 'Elec'
    elif name == 'Books':
        return 'Book'
    elif name == 'Sports':
        return 'sports'

auctions/templates/auctions/categories.html
{% extends 'auctions/layout.html' %}
{% load static %}
{% block title %}
    Category-List
{% endblock %}
{% block body %}
    <h4 class="heading">Available Categories</h4>
    <ul class="list-group">
        {% for category in categories %}
        <a href="{% url 'auctions:category' category%}" class="list-group-item listItem">{{category}}</a>
        {% endfor%}
    </ul>

{% endblock %}

auctions/templates/auctions/category.html
{% extends 'auctions/layout.html' %}
{% load static %}
{% block title %}
    Category-{{category}}
{% endblock %}
{% block body %}
    <h1 class="heading">Category: {{category}}</h1>
    <div class="container">
        <div class="row justify-content-md-center">
        {% for list in auctionlist %}
            <div class="col-12 col-sm-6 col-md-4">
                <div class="item">
                        <a class="aHover" href="{% url 'auctions:item' list.id%}">
                        <div class="picture">
                            {% if list.image %}
                            <img src="{{list.image.url}}" alt="image">
                            {% endif %}
                        </div>
                        <div class="title">
                            <h4>{{list.title}}</h4>
                        </a>
                        <div class="description">
                            {{list.description}}
                        </div>
                        <p>Price: <span>{{list.initialBid}}$</span></p>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
        </div>
{% endblock %}

auctions/templates/auctions/create.html
{% extends 'auctions/layout.html' %}
{% load static %}
{% block title %}
    Create Listing
{% endblock %}
{% block body %}
    <h2 class="heading">Create Listing</h2>
    <form action="{% url 'auctions:create' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="formContainer">
            <div class="form-group form">
                {{ form }}
            </div>
            <div class="btnDiv">
                <input type="submit" value="Create" class="btn btn-primary adjustBtn">
            </div>
        </div>
    </form>

{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}
{% block title %}
    Auction Listing
{% endblock %}
{% block body %}
    <h2 class="heading">Active Listings</h2>
    <div class="hammer">
        <div class="line"></div>
        <img src="{% static 'auctions/Pictures/hammer.png' %}" alt="image">
        <div class="line"></div>
    </div>

    <div class="container">
    <div class="row justify-content-md-center">
    {% for list in auctionlist %}
        <div class="col-12 col-sm-6 col-md-4">
            <div class="item">
                    <a class="aHover" href="{% url 'auctions:item' list.id%}">
                    <div class="picture">
                        {% if list.image %}
                        <img src="{{list.image.url}}" alt="image">
                        {% endif %}
                    </div>
                    <div class="title">
                        <h4>{{list.title}}</h4>
                    </a>
                    <div class="description">
                        {{list.description}}
                    </div>
                    <p>Price: <span>{{list.initialBid}}$</span></p>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
    </div>
{% endblock %}
          

auctions/templates/auctions/item.html
{% extends 'auctions/layout.html' %}
{% load static %}
{% block title %}
    {{auctionList.title}}-Listing
{% endblock %}
{% block body %}
    <h2 class="heading">Listing: {{auctionList.title}}</h2>
    <div class="hammer">
        <div class="line"></div>
        <img src="{% static 'auctions/Pictures/hammer.png' %}" alt="image">
        <div class="line"></div>
    </div>
    
    <form class="inline" action="{% url 'auctions:watchList' auctionList.id%}" method="post">
        {% csrf_token %}
        {% if isWatchListItem %}
        <input type="submit" class="btn btn-outline-danger btnWatch" value="Remove from WatchList"></input>
        {% else %}
            <input type="submit" class="btn btn-outline-primary btnWatch" value="Add To WatchList"></input>
        {% endif %}
    </form>
    {% if isOwner and auctionList.isActive %}
        <form class="inline" action="{% url 'auctions:item' auctionList.id%}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-outline-warning" value="Close Biding">
        </form>
    {% endif %}
        <div class="picContainer">
            {% if auctionList.image %}
            <img src="{{auctionList.image.url}}" alt="image">
            {% endif %}
        </div>
        <div class="desc">
            <h3>Description</h3>
            {{auctionList.description}}
        </div>
        <div class="price">
           Current Bid :
           {% if highestBid %} 
           {{highestBid}}$
           {% else %}
           {{auctionList.initialBid}}$
           {% endif %}

        </div>
        {% if message %}
        <div class="alert alert-danger">
            {{message}}
        </div>
        {% endif %}
        {% if isWinner %}
        <div class="alert alert-success">
            Congratulation! You Won The Auction.
        </div>
        {% endif %}
        {% if auctionList.isActive and not isOwner%}
        <form class="bidForm" action="{% url 'auctions:item' auctionList.id%}" method="post">
            {% csrf_token %}
            <input type="number" name="bidInput" class="form-control" placeholder="Bid" min="{{highestBid}}">
            <input type="submit" class="btn btn-primary" value="Place Bid">
        </form>
        {% endif %}
        <div class="detail">
            <h3>Details</h3>
            <ul>
                <li>Listed by: <span>{{auctionList.owner.username}}</span></li>
                <li>Category: <span>{{auctionList.get_category_full_name}}</span></li>
                <li>Initial Bid: <span>{{auctionList.initialBid}}$</span></li>
                <li>Total no(s) of Bid(s): <span>{{noOfBids}}</span></li>
                <li>Listing Status: <span>{{status}}</span></li>
            </ul>
        </div>
        <h2 class="heading">Comments Section</h2>
        <form class="bidForm" action="{%url 'auctions:item' auctionList.id%}" method="post">
            {% csrf_token %}
            {{ commentForm }}
            <input type="submit" name="comment_submit" class="btn btn-primary" value="Comment">
        </form>
        {% if comments %}
        <div class="commentContainer">
            {% for comment in comments %}
            <div class="card bg-light mb-3">
                <div class="card-body">
                  <h5 class="card-title">{{comment.commentor}}</h5>
                  <p class="card-text">{{comment.Comment}}</p>
                </div>
              </div>
            {% endfor %}
        </div>
        {% endif %}
{% endblock%}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Auctions{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">

</head>

<body>
    <div class="logo">
        <img src="{% static 'auctions/Pictures/logo.png' %}" alt="img">
    </div>
    <div>
    </div>
    <div id="navbarNav">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:create' %}">Create Listing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:watch' %}">WatchList</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
            </li>

        </ul>
        <ul class="nav navEnd">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <strong class="signedInUser nav-link">{{ user.username }}</strong>
            </li>
            <li class="nav-item navItem">
                <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item navItem">
                <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
            </li>
            <li class="nav-item navItem">
                <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
            </li>
            {% endif %}
        </ul>
    </div>
    {% block body %}
    {% endblock %}
</body>

</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}
{% block title %}
    Auction-Login
{% endblock %}
{% block body %}

    <h2 class="heading">Login</h2>

    {% if message %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="formContainer lgForm">
            <div class="form-group form">
                <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group form">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <input class="btn btn-primary" type="submit" value="Login">
            <div>
                Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>
            </div>
        </div>
    </form>


{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}
{% block title %}
    Auction-Register
{% endblock %}
{% block body %}

    <h2 class="heading">Register</h2>

    {% if message %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endif %}

    <form class="formContainer lgForm" action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group form">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group form">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group form">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group form">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
        <div>
            Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>
        </div>
    </form>
    

{% endblock %}

auctions/templates/auctions/watchList.html
{% extends 'auctions/layout.html' %}
{% load static %}

{% block title %}
    WatchList
{% endblock %}

{% block body %}

{% if isEmpty %}
<div class="alert alert-info" role="alert">
    There is no Item in your watch List
</div>
{% else %}
<h2 class="heading">WatchList</h2>
<div class="hammer">
    <div class="line"></div>
    <img src="{% static 'auctions/Pictures/hammer.png' %}" alt="image">
    <div class="line"></div>
</div>
{% endif %}
<div class="container">
    <div class="row justify-content-md-center">
    {% for list in products %}
        <div class="col-12 col-sm-6 col-md-4">
            <div class="item">
                    <a class="aHover" href="{% url 'auctions:item' list.id%}">
                    <div class="picture">
                        {% if list.image %}
                        <img src="{{list.image.url}}" alt="image">
                        {% endif %}
                    </div>
                    <div class="title">
                        <h4>{{list.title}}</h4>
                    </a>
                    <div class="description">
                        {{list.description}}
                    </div>
                    <p>Price: <span>{{list.initialBid}}$</span></p>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
    </div>
{% endblock %}